### ISSUE TITLE
啥时候要写爬虫部分告诉我一声啊

### ISSUE THREAD

**Issue by paomian** [sdutlinux/gotit#1]
@zhwei 讨论讨论怎么写。

**Comment by defp** [comment]
主程同学分配任务吧

**Comment by paomian** [comment]
@lidashuang 主程你说

**Comment by liuzhe0223** [comment]
还没开始，就有star了

**Comment by zhwei** [comment]
怎么写。。。

**Comment by zhwei** [comment]
@paomian Python和Clojure之间怎么通信，确定走HTTP了？还有啥更方便的方法么？

**Comment by paomian** [comment]
@zhwei 你想走啥 tcp 么？

**Comment by defp** [comment]
通啥信，结果放数据库

**Comment by zhwei** [comment]
凑，给用户用是需要实时的。。。

不过可以直接走异步哦，所有任务直接扔Redis也不错

**Comment by paomian** [comment]
@zhwei 这还不够蛋疼的呢，我接到请求放 redis 你在去取，你跑完了在放 redis ，我这边也要写个拿你返回数据的接口，我想着就烦。。。

**Comment by zhwei** [comment]
@paomian 异步有异步的好处，再说，这也不算麻烦多几个接口而已。

**Comment by Ma233** [comment]
用thrift!!!

**Comment by defp** [comment]
调个api而已，没必要搞太高大上啊
http啊

**Comment by darknessomi** [comment]
用 PB 啊

**Comment by zhwei** [comment]
挖个坑

**Comment by paomian** [comment]
老师想重写，你得告诉新同学有啥坑啊

**Comment by darknessomi** [comment]
深埋~

**Comment by paomian** [comment]
@zhwei

**Comment by zhwei** [comment]
能有啥坑。。。就一个小爬虫

**Comment by paomian** [comment]
新同学在写着，我都看到了，你别挖坑了，这个坑有人填了。。。

**Comment by zhwei** [comment]
那就关了呗，我想先写个Parser。。。

**Comment by lyu-huiyang** [comment]
各位学长好，年前管老师要求gotit重写，顺便给校报那边迁到微信端。 目前我正在写，原来的webpy框架看不太懂，web用的是目前在学习的flask写的，还没写到数据库，目前还是实时爬取。第一次写正儿八经的项目，目前水平有限，学长请轻喷。。https://github.com/lvhuiyang/new_gotit 不足之处还请各位学长指点

**Comment by zhwei** [comment]
挺好挺好，web.py 都都要死了的节奏了，有事情多问问汤汤老师，趁他在学校多压榨。

**Comment by lyu-huiyang** [comment]
好滴好滴。
